#!/usr/bin/env python

import cgi
import cgitb
from hg_helper import check_repo_name
from grp import getgrgid
import os
import sys

#cgitb.enable()
cgitb.enable(display=0)

repo_root = "/repo_local/mozilla"

print "Content-Type: text/plain"
print

form = cgi.FieldStorage()
if not form or not form.has_key("repo"):
    print "Need a repository to check"
    sys.exit(1)

repo = form.getfirst("repo", "")
if not check_repo_name(repo):
    print "You've included some illegal characters in your repo name"
    sys.stderr.write("Warning: illegal characters in repo name\n")
    sys.exit(1)
# ensure that the repo is within repo_root
if repo.find('/../') != -1:
    print "That's not allowed"
    sys.stderr.write("Warning: /../ found in a repo name.\n")
    sys.exit(1)

dir = "%s/%s" % (repo_root, repo)

if not (os.path.isdir(dir) and os.path.isdir(dir + "/.hg")):
    print "%s is not an hg repository" % repo
    sys.exit(1)

try:
    fdata = os.stat(dir)
except:
    sys.stderr.write("Warning: Couldn't stat %s" % dir)
    print "Could not read %s" % repo
    sys.exit(1)

gid = fdata.st_gid
group = getgrgid(gid)[0]
print group

# Local variables:
# mode: python
# indent-tabs-mode: nil
# tab-width: 4
# end:
